from fastapi import FastAPI, UploadFile, File
from pydantic import BaseModel
import pandas as pd
import os
import logging
import re
from dotenv import load_dotenv

from langchain_openai import AzureChatOpenAI
from langchain.tools import tool
from langchain.agents import create_agent

# -------------------------------------------------
# Logging
# -------------------------------------------------
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

# -------------------------------------------------
# App & Env
# -------------------------------------------------
load_dotenv()
app = FastAPI()

DATAFRAME: pd.DataFrame | None = None
SCHEMA: dict | None = None

# -------------------------------------------------
# LLM
# -------------------------------------------------
llm = AzureChatOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    deployment_name=os.getenv("AZURE_CHAT_MODEL_DEPLOYMENT"),
    temperature=0
)

# -------------------------------------------------
# TOOL 1: GET SCHEMA
# -------------------------------------------------
@tool(description="Returns CSV schema: column names, data types, and first 5 rows only.")
def get_schema() -> str:
    """
    Used by LLM to understand CSV structure before creating Excel-like formulas.
    """
    global DATAFRAME, SCHEMA

    if DATAFRAME is None:
        logger.warning("get_schema called but no CSV uploaded.")
        return "No CSV uploaded."

    SCHEMA = {
        "columns": {col: str(dtype) for col, dtype in DATAFRAME.dtypes.items()},
        "preview": DATAFRAME.head(5).to_dict(orient="records")
    }

    
    logger.info(f"Schema prepared and sen to llm")
    return str(SCHEMA)

# -------------------------------------------------
# TOOL 2: EXECUTE SCHEMA WITH EVAL
# -------------------------------------------------
@tool(description="Executes dynamic Pandas expressions generated by the LLM on the uploaded CSV.")
def execute_schema(formula: str) -> str:
    """
    Executes LLM-generated Pandas expressions on CSV.
    Formula must use 'df' as the DataFrame variable.
    """
    global DATAFRAME

    if DATAFRAME is None:
        logger.warning("get_schema called but no CSV uploaded.")
        return "No CSV uploaded."

    dataframe = DATAFRAME.copy()  # Local copy for safety

    # Clean formula
    formula = formula.strip()
    logger.info(f"Received formula for execution: {formula}")
    try:
        # Try evaluating as single expression
        result = eval(formula, {"df": dataframe}, {})
        logger.info(f"Formula executed successfully with eval. Result type: {type(result)}")
    except SyntaxError:
        # If multi-line or assignment, use exec safely
        safe_locals = {"df": dataframe}
        exec(formula, {"df": dataframe}, safe_locals)
        # If LLM assigns 'result', get it; else fallback to df
        result = safe_locals.get("result", dataframe)

    # Convert DataFrame to list of dicts if needed
    if isinstance(result, pd.DataFrame):
        return result.to_dict(orient="records")
    elif isinstance(result, pd.Series):
        return result.to_list()
    else:
        return str(result)

# -------------------------------------------------
# AGENT
# -------------------------------------------------
agent = create_agent(
    model=llm,
    tools=[get_schema, execute_schema],
    system_prompt="""
You are an Excel/Pandas assistant.
Process:
1. Call get_schema to understand CSV columns, types, and preview.
2. Generate an Excel-style or Python Pandas formula to answer the user's question.
3. Call execute_schema with ONLY the formula.
Never explain the formula.
Never return raw data unless requested.
"""
)

# -------------------------------------------------
# API Models
# -------------------------------------------------
class ChatRequest(BaseModel):
    message: str

# -------------------------------------------------
# UPLOAD CSV
# -------------------------------------------------
@app.post("/upload")
async def upload_csv(file: UploadFile = File(...)):
    global DATAFRAME
    DATAFRAME = pd.read_csv(file.file)
    logger.info(f"CSV uploaded | shape={DATAFRAME.shape}")
    return {"status": "CSV uploaded successfully"}

# -------------------------------------------------
# CHAT
# -------------------------------------------------
@app.post("/chat")
async def chat(req: ChatRequest):
    result = agent.invoke({"messages": [{"role": "user", "content": req.message}]})
    answer = result["messages"][-1].content
    logger.info(f"Final answer: {answer}")
    return {"response": answer}